name: time_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: 3.2.1

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_login_facebook: ^1.5.0+1
  flutter_screenutil: ^5.5.3+1
  google_sign_in: ^5.3.3
  intl: ^0.17.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  provider: ^6.0.3
  rxdart: ^0.27.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  rxdart: ^0.27.5

flutter:
  uses-material-design: true
  assets:
    - images/
